### ISSUE TITLE
Allow for dropdown/accordion/expanding items in site nav...

### ISSUE THREAD

**Issue by rdwatters** [gohugoio/gohugoioTheme#10]
This is just another conversational point similar to https://github.com/budparr/gohugo-theme/issues/9.

With the current hugodocs.info, users can open and close sections to go directly to pages, even on mobile. Do you think this would provide additional utility for mobile users?

**Comment by budparr** [comment]
I've considered this, and will revisit.

**Comment by jmooring** [comment]
No longer relevant.
