### ISSUE TITLE
Do the .Next/.Prev -> .PrevPage/.NextPage refactoring on updating to Hugo v0.50

### ISSUE THREAD

**Issue by kaushalmodi** [gohugoio/gohugoioTheme#102]
Ref: https://github.com/gohugoio/hugo/pull/5252

**Comment by jmooring** [comment]
This was resolved a long time ago. The only next/prev links are the symbols above the TOC in the right sidebar, and the behavior is correct.

![image](https://github.com/gohugoio/gohugoioTheme/assets/335669/ab92648e-3ece-46d8-9384-63be17ec2a95)
