### ISSUE TITLE
Create an opt-in to Google Analytics Tracking on gohugo.io websites

### ISSUE THREAD

**Issue by onedrawingperday** [gohugoio/gohugoioTheme#106]
I noticed that currently Google Analytics tracking is enabled across the board on all gohugo.io websites.

See: https://github.com/search?q=org%3Agohugoio+UA-7131036-4&type=Code

Please consider disabling it. 

If you see value in tracking visitors then maybe there should be an opt-in or opt-out banner. 

Personally I am not in favour of tracking visitors for an Open Source Project but then again this is not my call.

cc: @bep @budparr @digitalcraftsman @regisphilibert @kaushalmodi @moorereason

**Comment by budparr** [comment]
I think there should be analytics. Having that data helps determine how people use the site, and thus can be useful for design. What's more, for the long-term viability of a an open source project, there should be a measure of users, and I think web traffic is a better measure than stars. 

However, I agree, opt-in is appropriate. We have that capability now (in the internal ga template). I haven't done that myself, being U.S.-centric, but happy to tackle it.

**Comment by onedrawingperday** [comment]
>I agree, opt-in is appropriate. We have that capability now (in the internal ga template). I haven't done that myself, being U.S.-centric, but happy to tackle it.

Yes we had work done to this end in the GDPR update back in May 2018.

Some kind of opt-in banner is needed so that when a user clicks:

Yes ---> The GA script loads
No----> The script doesn't load

Also once a choice is made the banner shouldn't appear again for an X amount of time. 
Perhaps a Local Storage key will do.

Thanks for offering to tackle this.

**Comment by budparr** [comment]
Perhaps rename the issue to reflect just opt-in. And that assumes others agree.

**Comment by onedrawingperday** [comment]
>Perhaps rename the issue to reflect just opt-in. And that assumes others agree.

Done.

**Comment by coliff** [comment]
A quick easy-win which helps with protecting users privacy (and GDPR compliance) a bit would be to add IP address anonymization to the Google Analytics config for all users. Just add:
`'anonymize_ip': true`
to: https://github.com/gohugoio/gohugoioTheme/blob/master/layouts/partials/gtag.html
There's almost no downside to doing this (other than the accuracy of geographical location of users at the city-level is impacted slightly...  https://support.google.com/analytics/answer/2763052
