### ISSUE TITLE
Search text color is transparent in Safari iOS

### ISSUE THREAD

**Issue by onedrawingperday** [gohugoio/gohugoioTheme#119]
It seems that something changed recently and now when typing in the search box of the Hugo website the text is transparent. 

I see this behavior in mobile Safari, iOS 12.

I’m afraid that I can’t provide a screenshot as I’m on the go at the moment.

**Comment by onedrawingperday** [comment]
Here is the screenshot:

![](https://imgur.com/Bzz0EHE)

**Comment by XhmikosR** [comment]
Can you try with `color: #fff`? I don't have an iOS device to debug this.

The cause might be the CSS minifier BTW. You can confirm if you run the debug build locally.

**Comment by XhmikosR** [comment]
Or it could be the algolia styles.

@onedrawingperday can you try https://xmr-hugo-dev.netlify.com/?

**Comment by onedrawingperday** [comment]
@XhmikosR

The problem is fixed in the link you posted in Safari iOS.
