### ISSUE TITLE
On Mobile in "Use Site Configuration Parameter" section, the tabs come over the navbar

### ISSUE THREAD

**Issue by ankitskvmdam** [gohugoio/gohugoioTheme#125]
On Mobile in "Use Site Configuration Parameter" section, link: "https://gohugo.io/templates/introduction/", tabs come over the navbar.
I have also attached the screenshot for reference.
![hugo](https://user-images.githubusercontent.com/22586210/52272088-a7810200-296b-11e9-8eb8-612f2ef8cbf9.jpg)

**Comment by jmooring** [comment]
This was resolved a long time ago.
