### ISSUE TITLE
Theme item on large display take up 100% width

### ISSUE THREAD

**Issue by joshmorel** [gohugoio/gohugoioTheme#127]
![image](https://user-images.githubusercontent.com/10546720/54995549-5968a200-4f9d-11e9-9c88-9277db392181.png)

I see they are using `w-30-ns` class which would address this except the class does't exist in the CSS. There is `w-20-ns` and `w-50-ns` but no `w-30-ns`.

**Comment by budparr** [comment]
This seems to be an error with the way we purge the CSS file now. I'll check it out.
