### ISSUE TITLE
Duplicates? Both app.js and app.bundle.js are currently included

### ISSUE THREAD

**Issue by anthonyfok** [gohugoio/gohugoioTheme#129]
While packaging the latest Hugo 0.55.x for Debian, I was warned by the Lintian checking tool about the necessity to provide the missing source files of app.js and app.bundle.js, which eventually alerted me to the fact that both app.js and app.bundle.js exist, probably as duplicates?

That is despite a relatively recent commit 3b33d5ad200c57f8adbaf75f9c54ca3cc0cc97f8 "Update asset dependencies and adopt Hugo Pipes" on 2018-11-25 by @budparr in which the webpack output file was changed from static/dist/app.bundle.js to assets/output/js/app.js completely.  However, it appears to be _partially_ overridden after a git merge operation somewhere down the line.  In particular, the file app.bundle.js was resurrected, and layouts/index.headers still linking to app.bundle.js.

As I am still a newbie in webpack and Hugo pipes, I thought I'd better leave it to the experts by filing an issue before I forget.  :-)

Many thanks!

/cc @budparr, @bep

**Comment by bep** [comment]
I don't see this behaviour now?

**Comment by jmooring** [comment]
No longer relevant.
