### ISSUE TITLE
Editing the footer?

### ISSUE THREAD

**Issue by writarium** [gohugoio/gohugoioTheme#136]
I just discovered Hugo two days ago and then discovered this theme. I won't describe on length about how much I love it!

Jumping straight to my issue. I was wondering how do I go about editing like removing or adding contents to it? I found ways of editing items like the sidebar or Header but haven't found anything for the footer. 

Could anyone please give directions on how do I go about it?

Much thanks!

Also, apologies if this is the wrong place to ask. I would be very thankful if any links/resources could be shared where I can delve into it deeper. 

![](https://i.imgur.com/OwnZT6h.png)

**Comment by digitalcraftsman** [comment]
Hello @writarium,

the template for the footer shown in the image above can be found [here](https://github.com/gohugoio/gohugoioTheme/blob/9d6c945dcb655c2b6295c0f5fad23a92b0a9e5f3/layouts/partials/site-footer.html). For further discussions, please use the official [Hugo forum](https://github.com/gohugoio/gohugoioTheme/blob/9d6c945dcb655c2b6295c0f5fad23a92b0a9e5f3/layouts/partials/site-footer.html).
