### ISSUE TITLE
Docs - Quick Start - Add a Theme section not displaying properly

### ISSUE THREAD

**Issue by rishiip** [gohugoio/gohugoioTheme#137]
While visiting following url, `Add a Theme` section is not displaying properly.

https://gohugo.io/getting-started/quick-start/#step-3-add-a-theme

<img width="1280" alt="Screenshot 2019-09-15 15 56 33" src="https://user-images.githubusercontent.com/7964257/64920188-034d1c80-d7d2-11e9-8396-8673ca49ea65.png">

@bep I am able to pick it up. Please let me know.

**Comment by writarium** [comment]
Is your mouse hovered over the piece of code? From what I understand, hovering the mouse over long lines of code stretches the code block further right.

https://gfycat.com/scratchymaleerin

**Comment by rishiip** [comment]
@writarium Yes.

**Comment by jmooring** [comment]
This was resolved a long time ago.
