### ISSUE TITLE
I cannot build this project

### ISSUE THREAD

**Issue by bep** [gohugoio/gohugoioTheme#139]
The instructions tell me to build from `src`, and that has admittedly worked beofore -- now any build variation gives me an webpack error:

```
No configuration file found and no output filename configured via CLI option.
A configuration file could be named 'webpack.config.js' in the current directory.
```
/cc @budparr @XhmikosR any idea? I must admit that I do not understand the build setup, but we need to fix this ASAP.

**Comment by bep** [comment]
OK, doing a CSS change and building from the top level works? Is the `src` folder now superflous?

**Comment by XhmikosR** [comment]
You are not supposed to be in src. You need to be in root and use one of the scripts defined in package.json

**Comment by bep** [comment]
>You are not supposed to be in src.

So, then I assume that **the old build dir (src)** can safely be deleted?

**Comment by XhmikosR** [comment]
No, that is the src dir. The assets dir is the dist dir AFAICT.

**Comment by XhmikosR** [comment]
Actually wait, yes, it seems that the src dir can be removed. See if the commands from root run fine after you remove it (all of the scripts).
