### ISSUE TITLE
Toggle for dark/light code theme in all code blocks

### ISSUE THREAD

**Issue by rdwatters** [gohugoio/gohugoioTheme#18]
Not saying this needs to be a requirement for launch (if at all), but only continuing the conversation from the current Hugo docs concept repo. I already think your visual design decisions make the content more readable, so this may be superfluous at this point:

https://github.com/rdwatters/hugo-docs-concept/issues/27

**Comment by jmooring** [comment]
Duplicate of https://github.com/gohugoio/gohugoioTheme/issues/130
