### ISSUE TITLE
Use of definition list for functions Quick Reference...

### ISSUE THREAD

**Issue by rdwatters** [gohugoio/gohugoioTheme#19]
I like the blocks/cards being used for the index/list pages, but I wonder if there is more value in keeping the functions reference semantic as a `<dl>`? I usually find longer alphabetical lists easier to scan as single columns. Thoughts?

**Comment by budparr** [comment]
Are you talking about code or visual? It looks like there's something missing from your post here.

**Comment by rdwatters** [comment]
Forgot to wrap the `<dl>` in back ticks on my phone :smile: 

> Are you talking about code or visual?

Both, maybe?

**Comment by budparr** [comment]
well they're listed linearly in the sidebar and listing them as one long list would make for a very long page. If you mean to list the landing page as the actual reference—because now they're just page summaries like every other page type—then that's something, though I'd still say one long line is probably too much.

**Comment by rdwatters** [comment]
> because now they're just page summaries like every other page type

I think you mean page `.Description`, no? (This is for my own clarification and the terms have been muddied elsewhere.)

**Comment by budparr** [comment]
I wasn't speaking of tags, just that each of those list pages (home, section) output boxes with titles and summaries of the pages within.

**Comment by rdwatters** [comment]
Oops. Looks like we crossed streams! I was just updating my comment above.

**Comment by budparr** [comment]
> One quick thing to note would be to run the titles in these list views through markdownify since they contains markdown content.

For everything, or just the functions? What sort of Markdown do they have (just curious)? I often do that for my sites so my clients can use italics in titles.

**Comment by rdwatters** [comment]
For functions at least, mostly inline `<code>` (see `now` and `GetPage`).

> I often do that for my sites so my clients can use italics in titles.

That was my thinking too: more flexibility. Do you think this kills perf at built time? (See https://github.com/rdwatters/hugo-docs-concept/issues/44#issuecomment-292260458)

**Comment by budparr** [comment]
I strip everything out of descriptions because there meant to be a "what's inside" type of thing. Adding in code and then truncating them can lead to problems. And, yeah, build times might be a consideration here. I already hit them with consolidating templates (as I mentioned to you in Slack the other day).

**Comment by rdwatters** [comment]
What do you suggest? I can go ahead and remove any ``` if you think it's cleaner. I usually just use a a func (e.g., `plainify`), but I could also see that adding more overhead.

> as I mentioned to you in Slack the other day

You're talking about the 6-second build on ND? If so, gotcha :smile:

**Comment by budparr** [comment]
Actually, I just looked and I don't strip anything out. This is my code. It seems to be okay just not rendering that stuff, though I haven't looked closely:

```
  {{ if .context.Params.description  }}
        <p>
          {{ .context.Params.description  }}
        </p>
        {{ else }}
        <p>
          {{ .context.Summary  }}
        </p>
      {{ end }}
```

And, no I was talking about how I use one template for three different pages:
https://github.com/rdwatters/hugo-docs-concept/blob/bp/theme-design/layouts/index.html

I have to evaluate if it does too much for build-time.

**Comment by jmooring** [comment]
No longer relevant.
