### ISSUE TITLE
Make it a generic theme for documentation

### ISSUE THREAD

**Issue by hsehdar** [gohugoio/gohugoioTheme#200]
This theme when applied in Hugo Documentation looks great and would like to have it as a generic theme for documentation of other projects. Would that be possible? I am referring to
![image](https://user-images.githubusercontent.com/50985509/115879000-cc87bf80-a466-11eb-887a-1d093ece1d42.png)

It should be as simple as executing 

`git submodule add https://github.com/theNewDynamic/gohugo-theme-ananke.git themes/ananke`

**Comment by jmooring** [comment]
This theme is tailored to the Hugo documentation site; it is not a general purpose theme.
