### ISSUE TITLE
Some issues with _headers

### ISSUE THREAD

**Issue by bep** [gohugoio/gohugoioTheme#23]
I had to make some adjustments to get the theme site up and running, see https://github.com/spf13/hugoThemesSite/blob/master/static/_headers

**Comment by budparr** [comment]
That policy works for me elsewhere, but I'll see if I can hone in on this to improve it. Here's our current security grade, which is a "D" so lots of room for improvement. 
https://observatory.mozilla.org/analyze.html?host=themes.gohugo.io

Also, it doesn't look like we're forcing SSL on Netlify, but can take that up elsewhere.

Thanks!

**Comment by XhmikosR** [comment]
Definitely set up SSL redirection. Also set up HSTS and submit to HSTS preload list.

CSP should be doable to, you just need to go through all the docs and see what you load from which origin. You can try https://addons.mozilla.org/en-us/firefox/addon/laboratory-by-mozilla/ but it will definitely need work from your side. Also, report-uri.io is your friend.

**Comment by coliff** [comment]
The site gets a **B-** score now which is much better so I suggest that this issue can be closed.
https://observatory.mozilla.org/analyze/gohugo.io
