### ISSUE TITLE
Godoc reference?`

### ISSUE THREAD

**Issue by rdwatters** [gohugoio/gohugoioTheme#24]
On the previous design, I included a button that would take users to the related official Godoc. This was especially useful in functions, for example. The motivation was to make the connection to Golang  because I know Steve has been charged with promoting/advocating/evangelizing the language. It also gives more close-to-the-metal descriptions of what's going on under the hood? Thoughts on whether we should add this back to the single-page templates for the docs?

**Comment by budparr** [comment]
It's there. Looks like when I carried it over I didn't add a name or icon for it. Here's the line https://github.com/budparr/gohugo-theme/blob/master/layouts/partials/toc.html#L10 and I can add it soon.

**Comment by budparr** [comment]
agree!
