### ISSUE TITLE
Add GitHub stars to site header...footer...or maybe not at all?

### ISSUE THREAD

**Issue by rdwatters** [gohugoio/gohugoioTheme#27]
FWIW, I feel your pain on the consequent blow to performance scores...

**Comment by budparr** [comment]
I'm in the camp that those stars are silly and not an important metric, so not worth the hit. Recognizing that that's just my opinion.

**Comment by rdwatters** [comment]
😆 I guess we could pitch it to the team and see if anyone feels strongly about it one way or the other...

**Comment by budparr** [comment]
You're welcome to. I have no interest in the endeavor.
