### ISSUE TITLE
Is the theme usable?

### ISSUE THREAD

**Issue by Skrillx13** [gohugoio/gohugoioTheme#302]
So is the theme actually usable, or no? I don't know if this counts as a "proper" issue, but how do you actually install the theme, and use it?

When I tried copying this theme to my themes directory, it gave me an error in the `site-footer.html` file. I delete the broken line of code, and get another error about `render-link.html`.

If this theme isn't usable, then may I please know when the theme is going to be ready? Thanks.

**Comment by jmooring** [comment]
This theme is for Hugo's documentation site. Please select a theme from https://themes.gohugo.io/.
