### ISSUE TITLE
Missed datatable shortcode from existing site....

### ISSUE THREAD

**Issue by rdwatters** [gohugoio/gohugoioTheme#31]
I'm guessing this was a result of switching themes from my previous design to the new one. I've added this quickly for the live site--apologies, in retrospect I should have submitted a PR and requested you to review--but said shortcode is largely to leverage @bep 's data files that are autogenerated from the code. **Note:** I've added said data file to the `data` folder as well. 

You can see this shortcode in play on the custom outputs page:

https://hugodocs.info/templates/output-formats/

I'll open up a separate issue for the table overflow inside body copy. Thanks!

**Comment by jmooring** [comment]
This was resolved a long time ago.
