### ISSUE TITLE
Display more tweets in the homepage design

### ISSUE THREAD

**Issue by rdwatters** [gohugoio/gohugoioTheme#32]
Maybe just another 2-4. Now that Hugo has its own Twitter handle--and is actively being called out, especially as of late--I'd like to make sure we show it's popularity. Thoughts? 

I'll take on the responsibility of keeping this updated....

cc/ @digitalcraftsman

**Comment by digitalcraftsman** [comment]
- https://twitter.com/aras_p/status/861157286823288832
- https://twitter.com/brijgogogo/status/841356782429716481
- https://twitter.com/ssddanbrown/status/818592118604083200
-

**Comment by budparr** [comment]
Being that it's content, I think we can move the tweets file up to the site level, don't you think?

**Comment by rdwatters** [comment]
Yup. I already did that. I mean displaying more than the current 4 tweets. Maybe 6/8 instead?

**Comment by budparr** [comment]
Sure.
- [ ] make the tweets a bit smaller
- [ ] make room for additional tweets
- [ ] consider more interesting display (slideshow, formatting, etc...)

**Comment by jmooring** [comment]
No longer relevant. Moved to Mastadon.
