### ISSUE TITLE
Add Apple TV-style hover effect to theme detail pages

### ISSUE THREAD

**Issue by jhabdas** [gohugoio/gohugoioTheme#35]
https://gist.github.com/onetechgenius/e7f3947597f8fd420cef652597979bc0

You know you want to...

**Comment by jhabdas** [comment]
Maybe not this extreme though 🤣 http://jakpetz.co.id/

**Comment by budparr** [comment]
Lovely. If we did want this :) it would go in the hugoThemesSite repo.

**Comment by jhabdas** [comment]
Thank you kindly for the info and feedback, Bud
