### ISSUE TITLE
Add logo-copyright to footer

### ISSUE THREAD

**Issue by bep** [gohugoio/gohugoioTheme#39]
Something ala:

"The Hugo logos are copyright © Steve Francia 2013–2017"

**Comment by digitalcraftsman** [comment]
Through addition of copyright + the netlify badge the height of the columns in the footer looks a bit unbalanced. @budparr might work around it by adapting the layout.

**Comment by bep** [comment]
Sure, but this will not be the last change from me that hasn't been via the "Hugo design board standards committee" :-)

**Comment by budparr** [comment]
@bep feel free to nudge me on something if it needs to be done right away. I had been holding off on this to combine with other work.
