### ISSUE TITLE
Need bolder font weight for "The world’s fastest framework ..."

### ISSUE THREAD

**Issue by bep** [gohugoio/gohugoioTheme#42]
![image](https://user-images.githubusercontent.com/394382/28089458-5ec3cd00-6689-11e7-9daa-7c9a4789d546.png)

Having this screaming slogan with 200 font weight does not make much visual sense.

**Comment by budparr** [comment]
That's funny. The last conversation I had on this was to make the font weight lighter because I had it heavier.

**Comment by bep** [comment]
That was not a conversation you had with me. The last conversation I had about this was to make it "title case", but we can discuss that later. Right now it needs some boldness.

**Comment by scottgallant** [comment]
@bep less is more :) 

Some examples from some of my favorite sites

<img width="751" alt="screen shot 2017-07-11 at 5 44 15 pm" src="https://user-images.githubusercontent.com/776019/28089821-a5cd81b0-6660-11e7-93fe-1a0477e42eac.png">

<img width="758" alt="screen shot 2017-07-11 at 5 44 19 pm" src="https://user-images.githubusercontent.com/776019/28089837-ae322cde-6660-11e7-9947-06b5628912c1.png">

...shameless plug ;) 
<img width="985" alt="screen shot 2017-07-11 at 5 44 28 pm" src="https://user-images.githubusercontent.com/776019/28089845-b27524a4-6660-11e7-9838-a71e5598c30a.png">

**Comment by bep** [comment]
@scottgallant your examples look great, but they cannot be compared to my screen shot above which looks badly unbalanced against that heavy logo. It need a 500 font weight.

**Comment by budparr** [comment]
I think the issue is the scale of the logo on some resolutions. I'll have a look.

**Comment by bep** [comment]
Also, this can also be fixed by increasing the font sizes:

**Comment by bep** [comment]
@budparr we need a fix for this issue before we can merge the new docs site into master, planned for this Sunday. I'm not familiar with the CSS build setup, so if you have no time to spare, we will just push it for another week.

https://github.com/gohugoio/hugoDocs/issues/37

**Comment by budparr** [comment]
@bep I'll work on it today.

**Comment by budparr** [comment]
@bep I bumped up the font weight. Not so sure I agree with the change, but recognize that it's subjective and would rather deal with it more thoroughly (looking how we can improve the page as a whole) after launch. I'll leave this open until you've had a chance to look at it. 

_I'm having some issues with my local connectivity, so may be slow to respond,_

**Comment by bep** [comment]
Thanks, I have pushed to https://next--gohugoio.netlify.com/ -- the final answer may be 200 font weight with a slightly bigger font size, but let us leave it like this for now.

**Comment by budparr** [comment]
Great. I'll close for now.
