### ISSUE TITLE
Yarn install fails

### ISSUE THREAD

**Issue by bep** [gohugoio/gohugoioTheme#43]
I don't know yarn so no idea how to fix it:

```bash
▶  yarn install
yarn install v0.18.1
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error An unexpected error occurred: "https://github.com/pocketjoso/css.git: invalid tar file".
```

**Comment by budparr** [comment]
I'll have a look. May just need to update some dependencies.

**Comment by rdwatters** [comment]
Would a `yarn upgrade` work here, @budparr? This *might* help:

https://github.com/yarnpkg/yarn/issues/1619

Many users seem to go the "try it over and over until it works" route...

**Comment by bep** [comment]
yarn upgrade fixed it.

**Comment by budparr** [comment]
I've removed Yarn, with an explanation in this commit: https://github.com/gohugoio/gohugoioTheme/commit/18a6f9e6732942688f7a92408cce963e17bace58
