### ISSUE TITLE
Updated date should pull from lastmod and not gitinfo...

### ISSUE THREAD

**Issue by rdwatters** [gohugoio/gohugoioTheme#44]
Per Gitter conversation. 

Git timestamps aren't as representative of actual content updates. For example, a small typo fix isn't really an update to the content.

**Comment by bep** [comment]
We have had this discussion before and it was the main reason behind the GitInfo feature: The last Git commit is the best compromise in this situation: Much better than the file last updated (misleading in many situations, but many have suggested that) and much better than some manually updated timestamp in front matter (which most people forget to update).

And typo fixes are important updates.

**Comment by budparr** [comment]
So should I revert this: https://github.com/gohugoio/gohugoioTheme/commit/4e024780ce51b63c08fe2bab7b36a45b825c1a38

**Comment by bep** [comment]
@budparr I added this https://github.com/gohugoio/gohugoioTheme/commit/bca6fbb27a0e52b14ee04b2a57e2f0db772fe361 a day or so ago, but I'm not sure what is best. Up to you, but we should use the `GitInfo` when available.

**Comment by bep** [comment]
On an added note: The field to use for the last update is always `Lastmod`, so this should be transparent from the template perspective.

**Comment by rdwatters** [comment]
It's a great feature, but that's not what I'm talking about.

Example: if a contributor changes three typos in the current Quick Start, we're telling new users that that quick starter is now "Updated" as of mid-July...when it hasn't been updated in well over a year...and it's actually *outdated*.  

In publishing, when you see "Updated," it is almost never a matter of a typographical fix: it's a substantive change. When there are small factual errors, these are also treated differently as errata. But if you want to treat content like code, go for it...but it's misleading.

**Comment by rdwatters** [comment]
>  The field to use for the last update is always Lastmod

This is what I'm suggesting: front matter. I never suggested "File last updated."

**Comment by bep** [comment]
>This is what I'm suggesting: front matter. I never suggested "File last updated."

OK, so we can close this issue? The theme pulls from `Lastmod`. It is up to the calling site (i.e. hugo docs) to `--enableGitInfo`.

**Comment by rdwatters** [comment]
So we're back to using the last git commit for the updated? I feel like we are just misconnecting on something very basic here.
