### ISSUE TITLE
We need GitHub style background for the "backticked text"

### ISSUE THREAD

**Issue by bep** [gohugoio/gohugoioTheme#46]
![image](https://user-images.githubusercontent.com/394382/28238928-1c79fd7e-695f-11e7-8d0d-b0e541a0bf04.png)

The current solution with just a monospaced font just looks weird and does not put enough emphasis on the backticked words and sentences.

I'm expecting some design gurus from the Forest to chime in with some references here, but this convention is so baked into people from years on GitHub that it has become the new standard for code documentation -- and is essential to have when writing (and reading) it.

**Comment by budparr** [comment]
@bep This is the fix:

```
code {
  background-color: rgba(27,31,35,0.05);
  padding: 0.2em;
  font-size: 85%;
  border-radius: 3px;
}
```
here: https://github.com/gohugoio/gohugoioTheme/blob/master/src/css/_code.css#L13

This mimics Github and I think works fine. 

<img width="713" alt="screen shot 2017-07-15 at 8 36 43 am" src="https://user-images.githubusercontent.com/115347/28239365-c5f0c1a2-6938-11e7-8042-c2294adf5a64.png">


I'm having a few local issues, but should be able to implement this in the theme this weekend if this is good for you. Are we working of the hugodocs repo now? 

One other thought: if we're going to be publishing all release notes in the news section, perhaps we should use sans-serif for the news altogether?

**Comment by bep** [comment]
Yes, I'm working on the `next` branch in `hugoDocs` -- but I'm flying mostly solo to get it into a publishable shape. When it is in master it is open for all ... and I guess it gets more motivating when people can actually see the result of the work done.
