### ISSUE TITLE
documentation navigation problem in Safari

### ISSUE THREAD

**Issue by jgreely** [gohugoio/gohugoioTheme#48]
[Mac OS X 10.11.6, Safari 10.1.1; and iOS 10.3.2 (iPad), Safari 10]

The sidebar navigation Javascript is partially broken in Safari, not allowing you to switch to another documentation section from a detail page. Works fine in Chrome and Firefox.

Repeat-by: go to https://gohugo.io/functions/format/, then click on any sidebar link that's not another function detail page ("About Hugo", "Templates", "Troubleshooting", etc). Nothing happens.

The behavior is the same on any second-level page (`/content-management/types/`, `/tools/frontends/`, etc).

**Comment by bep** [comment]
Confirmed.

**Comment by budparr** [comment]
Confirmed as well and I see the error in console. I'll check it out.

**Comment by budparr** [comment]
I fixed this in commit https://github.com/gohugoio/gohugoioTheme/commit/18141c496f18ac74bfef480403b4bbb69c44bbbe (I mistyped the issue # in the commit message).
