### ISSUE TITLE
dev: Style-changes lost on navigation in live-reload

### ISSUE THREAD

**Issue by bep** [gohugoio/gohugoioTheme#51]
I guess this is a caching/JS issue that I don't understand. I haven't noticed this on other sites, so I guess this is related to the JS/webpack/node build setup.

In `hugo server` with `npm start`:

1. Make a change that triggers a CSS change => reload OK
2. Navigate to another page => CSS change in 1) is lost
3. Do a hard reload of http://localhost:1313/dist/main.css => CSS change is back

The above is on `macOS` and `Chrome`.

This makes for a fairly lousy developer experience.

**Comment by bep** [comment]
And right when I created this issue, I now cannot recreate the above. I will report back.

**Comment by bep** [comment]
OK, I'm confused -- I think this is somehow related to #50 ... I.e. the whole `webpack` setup seems to be broken and the custom `highlightjs` config seems to have no effect. I tried to look at it, but with `webpack` you would have to put 50 monkeys in a room for 10 years to get it right.

**Comment by budparr** [comment]
Webpack appears to be working perfectly. I just made two test changes, one of them to the hljs.css file with no problem. As long as you have caching turned off there should be no issue. 

I'm happy to have a conversation about Webpack sometime, if you like.

**Comment by bep** [comment]
To be clear: I'm talking about the build setup described in the `/src` doc -- not sure what cache you are talking about.

**Comment by budparr** [comment]
I need to change that to reflect the move back to NPM from Yarn for the lock file, but I don't think that's your issue. I think your issue is browser cache. Under dev tools settings in Chrome make sure "Disable cache (while DevTools is open)" is checked (or use incognito mode). I don't believe that issue has anything to do with Webpack or the setup in the readme.

**Comment by bep** [comment]
OK, disabling the chrome cache seems to fix my issue. Thanks.

**Comment by bep** [comment]
Now everyone should be happy. Now finally the docs site looks very, very good in all aspects.

And note that this improvement was all about consistency and not about code highlighting (which could have looked very good when done right).

**Comment by bep** [comment]
One example being: 

![image](https://user-images.githubusercontent.com/394382/28387760-9d8595f8-6cd0-11e7-8760-46ec2bbec5bd.png)

![image](https://user-images.githubusercontent.com/394382/28387786-ae9afefa-6cd0-11e7-88d5-a45c7d69e77f.png)


(the padding issue in the first example is my fault ...)

It would be nice to have nice Highlighting with proper Golang templates support mixed with HTML, but nothing is much better than what we had.
