### ISSUE TITLE
We need a "star on GitHub" button in the top somewhere

### ISSUE THREAD

**Issue by bep** [gohugoio/gohugoioTheme#55]
Like it or not, Hugo's popularity is measured in GitHub stars (see https://www.staticgen.com/). I would have expected the release announcement of the new docs to increase that star count, but it stayed steady around 25 stars on the day of the announcement.

On the old site, we had a "star on GitHub" button with some Javascript. We should add that back in a visible place, maybe next to the Twitter icon.

This is the GA trend for the GitHub Hugo repo:

![image](https://user-images.githubusercontent.com/394382/28412197-ac5f5f1e-6d43-11e7-822d-ee337040d5b8.png)

/cc @spf13 @budparr @digitalcraftsman @rdwatters

**Comment by budparr** [comment]
I'll add the star button along with an [RSS button](https://github.com/gohugoio/hugoDocs/issues/64) tonight

**Comment by bep** [comment]
Wait with the rss that does not need to be in the top.

**Comment by budparr** [comment]
Okay

**Comment by rdwatters** [comment]
Agreed. Regrettably, I think it takes away from the cleanness of Bud's design a bit, but whether we like it or not, GH stars are an important metric for some  users.

**Comment by bep** [comment]
Note that we only want 1 Button, to main hugo repo
