### ISSUE TITLE
Titles of code blocks have bad contrast

### ISSUE THREAD

**Issue by digitalcraftsman** [gohugoio/gohugoioTheme#56]
The contrast ration between the grey-blue header of the code block and the blue background isn't very high.
![cb](https://user-images.githubusercontent.com/7010165/28420546-c8ae02fa-6d62-11e7-82ae-6c13b73c5dcf.png)

**Comment by crgeary** [comment]
This appears to be fixed now.

**Comment by digitalcraftsman** [comment]
That's right. The blue background has been removed which increased the contrast a lot.
