### ISSUE TITLE
Fix <titles>

### ISSUE THREAD

**Issue by bep** [gohugoio/gohugoioTheme#58]
![image](https://user-images.githubusercontent.com/394382/28545977-5ccd364a-70c9-11e7-97af-611417d974ed.png)

For the home: Do not repeat the site + page title.
For the single pages: Not sure, but make it smaller/less stuttery for the Docs site.

**Comment by budparr** [comment]
I'm picking up the site title from the [config](https://github.com/gohugoio/hugoDocs/blob/master/config.toml#L9): `title = "Hugo: A Fast and Flexible Website Generator"` just as a standard.

Do you think it's better to hard-code the title to fix the titles, or change the site title to "Hugo" and put the "A fast..." into a description site variable. My opinion is the latter. I think the title on the home page only serves the site title, so can also be changed in content. Sound good?

**Comment by bep** [comment]
> or change the site title to "Hugo" 

Yes.

I will do this. To see how it looks. The home page have a title "Hugo: A Fast and Flexible Website Generator", so the easy path is to just remove the Hugo prefix from that one.
