### ISSUE TITLE
Fix content width

### ISSUE THREAD

**Issue by budparr** [gohugoio/gohugoioTheme#59]
After [change to sans-serif](https://github.com/gohugoio/gohugoioTheme/commit/3f503abe268651f6bdfbd56d79f12dcff2fa32c2) the balance of body copy is off. 

- [ ] bump up body copy typeface (maybe, and judge line-height after change)
- [ ] change width of body copy

**Comment by jmooring** [comment]
The width was slightly increased with https://github.com/gohugoio/gohugoioTheme/pull/271.
