### ISSUE TITLE
Find an alternative to the code-box expand feature

### ISSUE THREAD

**Issue by budparr** [gohugoio/gohugoioTheme#60]
On desktop, code blocks that exceed the width of the column expanded on hover. This behavior is broken. 

We need to either a) drop the feature (eliminate [this code](https://github.com/gohugoio/gohugoioTheme/blob/master/src/js/codeblocks.js)), or b) find another way to accomplish it

**Comment by rdwatters** [comment]
Maybe a dull suggestion, but I'm a fan of just allowing `overflow-x: scroll`.

**Comment by XhmikosR** [comment]
IMO this is bad user experience. But if you insist so much on this, you can disable the behavior on small screens, say < 768px.

**Comment by jmooring** [comment]
The expanding code blocks were removed a while ago with https://github.com/gohugoio/gohugoioTheme/pull/261 in favor of overflow: auto.
