### ISSUE TITLE
ExampleSite to create a new website

### ISSUE THREAD

**Issue by localguru** [gohugoio/gohugoioTheme#68]
Hi,

is there an ExampleSite to start a new website with the `gohugoioTheme` theme. The only way I found was to cloned the hugoDocs and remove content I don't need.

Ciao
Marcus

**Comment by bep** [comment]
Please use https://discourse.gohugo.io/ for questions/troubleshooting. Also see  [Hugo Documentation](http://gohugo.io/overview/introduction/).
