### ISSUE TITLE
German umlauts not working in /docs navigation

### ISSUE THREAD

**Issue by localguru** [gohugoio/gohugoioTheme#70]
Hi,

using German umlauts in name variables is not working, e.g.:

```
[[menu.docs]]
  name = "Über Hugo"
  weight = 1
  identifier = "about"
  url = "/about/"
```

I tried `de` and `utf-8` for language code:

```
defaultContentLanguage = "de"
languageCode = "de-de"
```

Any ideas how to fix this?

Ciao!

**Comment by digitalcraftsman** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to the [Hugo Discussion Forum](https://discourse.gohugo.io/).  We prefer to use GitHub issues only for bugs and enhancements.

**Comment by localguru** [comment]
No problem. I thought this is a bug. I'll post it in the Hugo Discussion Forum.
