### ISSUE TITLE
Add in instructions on how to build theme with site and build assets

### ISSUE THREAD

**Issue by felicianotech** [gohugoio/gohugoioTheme#75]
Looks like CSS (and maybe other stuff) is being built with an asset manager. Which? Instructions?

**Comment by budparr** [comment]
Hey, @felicianotech The instructions and details on the tools (Webpack/Post-CSS) are in the readme of the SRC directory: https://github.com/gohugoio/gohugoioTheme/tree/master/src

**Comment by felicianotech** [comment]
This still needs info in the main readme, but that helps for now. Thanks.

**Comment by budparr** [comment]
I didn't put them in the main readme because the way the CSS is structured it doesn't typically need to be part of the build process.
