### ISSUE TITLE
Gopher is missing on the themes directory

### ISSUE THREAD

**Issue by DirtyF** [gohugoio/gohugoioTheme#80]
```gherkin
When I browse the theme directory
Then the gopher image is not displayed in the footer
And https://themes.gohugo.io/images/gopher-side_color.svg returns a 404
```

**Comment by budparr** [comment]
The image resides in the main website's repo, instead of the theme. We can either make the link a full link (quickest) or move the image (probably correct, but may be a pain for @bep). 

Thanks for pointing it out @DirtyF

**Comment by bep** [comment]
I will move it.

**Comment by bep** [comment]
Done.

**Comment by DirtyF** [comment]
![fancy_gopher_renee](https://user-images.githubusercontent.com/103008/37214103-46ecac4a-23b4-11e8-97fe-19b2d75be0ee.jpg)
