### ISSUE TITLE
Got error when tweets is not exists

### ISSUE THREAD

**Issue by LinuxSuRen** [gohugoio/gohugoioTheme#91]
Here is my config.toml
```
baseURL = "http://autotest.surenpi.com/"
languageCode = "zh-CN"
title = "PhoenixAutotest Docs"
theme = "gohugoioTheme"

[[gloabl.menu]]
  name = "文档"
  url = "/docs"
  identifer = "docs
```
When I run cmd 'hugo server', got error information below:

Building sites … ERROR 2018/04/28 11:57:21 Error while rendering "home" in "": template: /Users/mac/IdeaProjects/Github/phoenix-autotest/phoenix.docs/themes/gohugoioTheme/layouts/index.html:23:8: executing "main" at <partial "home-page-s...>: error calling partial: template: theme/partials/home-page-sections/tweets.html:9:22: executing "theme/partials/home-page-sections/tweets.html" at <sort $.Site.Data.hom...>: error calling sort: sequence must be provided

**Comment by jan-xyz** [comment]
I don't think that it is meant to be used with anything other than the hugoio websites. However, if you want to get the blog running, make sure you have [this file](https://github.com/gohugoio/hugoDocs/blob/master/data/homepagetweets.toml).
