### ISSUE TITLE
Invalid Netlify header directives

### ISSUE THREAD

**Issue by kaushalmodi** [gohugoio/gohugoioTheme#96]
I see this in Netlify log for the hugo docs site:

```
5:44:23 PM: Invalid header directives:
5:44:23 PM: - /_headers: /*
	*/
```

https://github.com/gohugoio/gohugoioTheme/blob/master/layouts/index.headers needs to be fixed.

**Comment by bep** [comment]
I somehow get a dejavu feeling about this issue. Are you sure you have not asked this before?

Also, have you checked that the headers actually works (the important part)?

**Comment by kaushalmodi** [comment]
> Are you sure you have not asked this before?

Short deja vu.. I opened this issue on hugoDocs, closed there and reopened here :P. But other than that, asking this the first time :)

>

Looks like the headers work.. as Netlify is probably ignoring the `*/` line. Here are the headers I read for main.css on Firefox:

![image](https://user-images.githubusercontent.com/3578197/42787038-ab87b0e6-8926-11e8-82ea-8b68808b5908.png)

**Comment by bep** [comment]
OK, but I have had this discussion before. And as I remember it, there was a mismatch between the validator and the ... actual implementation in Netlify. i much prefer a working solution vs a broken solution that passes a broken validation.

**Comment by kaushalmodi** [comment]
OK, but just out of curiosity, would `*/` work the same as just `/`? The latter is part of the default examples on their headers validation page.

**Comment by bep** [comment]
>OK, but just out of curiosity, would just / work the same as */? 

You need to ask Netlify and not me. This is not important in relations to ... a bunch of important things.
