### ISSUE TITLE
Unused assets (js, css) inside the demo of the theme

### ISSUE THREAD

**Issue by serg** [gohugoio/gohugoioTheme#99]
I have created an issue inside the hugoThemes repository, but I think it should be here.
Here is: https://github.com/gohugoio/hugoThemes/issues/409

I think it's related with the Netlify configs located at here:
https://github.com/gohugoio/hugo/blob/master/docs/themes/gohugoioTheme/layouts/index.headers

**Comment by onedrawingperday** [comment]
I looked into this issue a bit yesterday and I noticed that this is an issue with Chrome only.

In Firefox the CSS and JS assets of the Hugo Site are not requested.

**Comment by serg** [comment]
I am also confirms this. This issue reaching out in Chrome only.

Perhaps, the good solution is adding the exclude pattern for the `/theme/*` url to the config if the Netlify provides this ability.

**Comment by jmooring** [comment]
No longer relevant.
